from django.urls import path
from . import views
import datetime
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", views.home_view, name="register"),

    path("metode_pembelajaran/<email>/<nama_lengkap>/<nomor_telefon>/<program_studi>/<angkatan>/<universitas>/<info_torche>/", views.metode_pembelajaran, name="metode_pembelajaran"),

    path("mata_kuliah/<email>/<nama_lengkap>/<nomor_telefon>/<program_studi>/<angkatan>/<universitas>/<info_torche>/<metode_pembelajaran>/<jumlah_sesi_yang_diikuti>/", views.mata_kuliah, name="mata_kuliah"),
    
    path("session_cse/<email>/<nama_lengkap>/<nomor_telefon>/<program_studi>/<angkatan>/<universitas>/<info_torche>/<metode_pembelajaran>/<jumlah_sesi_yang_diikuti>/<mata_kuliah>", views.session_cse, name="session_cse"),
    path("session_cem/<email>/<nama_lengkap>/<nomor_telefon>/<program_studi>/<angkatan>/<universitas>/<info_torche>/<metode_pembelajaran>/<jumlah_sesi_yang_diikuti>/<mata_kuliah>", views.session_cem, name="session_cem"),
    path("session_cet/<email>/<nama_lengkap>/<nomor_telefon>/<program_studi>/<angkatan>/<universitas>/<info_torche>/<metode_pembelajaran>/<jumlah_sesi_yang_diikuti>/<mata_kuliah>", views.session_cet, name="session_cet"),
    path("session_cps/<email>/<nama_lengkap>/<nomor_telefon>/<program_studi>/<angkatan>/<universitas>/<info_torche>/<metode_pembelajaran>/<jumlah_sesi_yang_diikuti>/<mata_kuliah>", views.session_cps, name="session_cps"),
    path("session_cre/<email>/<nama_lengkap>/<nomor_telefon>/<program_studi>/<angkatan>/<universitas>/<info_torche>/<metode_pembelajaran>/<jumlah_sesi_yang_diikuti>/<mata_kuliah>", views.session_cre, name="session_cre"),
    path("session_eec/<email>/<nama_lengkap>/<nomor_telefon>/<program_studi>/<angkatan>/<universitas>/<info_torche>/<metode_pembelajaran>/<jumlah_sesi_yang_diikuti>/<mata_kuliah>", views.session_eec, name="session_eec"),
    path("session_fac/<email>/<nama_lengkap>/<nomor_telefon>/<program_studi>/<angkatan>/<universitas>/<info_torche>/<metode_pembelajaran>/<jumlah_sesi_yang_diikuti>/<mata_kuliah>", views.session_fac, name="session_fac"),
    path("session_fca/<email>/<nama_lengkap>/<nomor_telefon>/<program_studi>/<angkatan>/<universitas>/<info_torche>/<metode_pembelajaran>/<jumlah_sesi_yang_diikuti>/<mata_kuliah>", views.session_fca, name="session_fca"),
    path("session_fch/<email>/<nama_lengkap>/<nomor_telefon>/<program_studi>/<angkatan>/<universitas>/<info_torche>/<metode_pembelajaran>/<jumlah_sesi_yang_diikuti>/<mata_kuliah>", views.session_fch, name="session_fch"),
    path("session_fht/<email>/<nama_lengkap>/<nomor_telefon>/<program_studi>/<angkatan>/<universitas>/<info_torche>/<metode_pembelajaran>/<jumlah_sesi_yang_diikuti>/<mata_kuliah>", views.session_fht, name="session_fht"),
    path("session_fmt/<email>/<nama_lengkap>/<nomor_telefon>/<program_studi>/<angkatan>/<universitas>/<info_torche>/<metode_pembelajaran>/<jumlah_sesi_yang_diikuti>/<mata_kuliah>", views.session_fmt, name="session_fmt"),
    path("session_fpm/<email>/<nama_lengkap>/<nomor_telefon>/<program_studi>/<angkatan>/<universitas>/<info_torche>/<metode_pembelajaran>/<jumlah_sesi_yang_diikuti>/<mata_kuliah>", views.session_fpm, name="session_fpm"),
    path("session_fp1/<email>/<nama_lengkap>/<nomor_telefon>/<program_studi>/<angkatan>/<universitas>/<info_torche>/<metode_pembelajaran>/<jumlah_sesi_yang_diikuti>/<mata_kuliah>", views.session_fp1, name="session_fp1"),
    path("session_fp2/<email>/<nama_lengkap>/<nomor_telefon>/<program_studi>/<angkatan>/<universitas>/<info_torche>/<metode_pembelajaran>/<jumlah_sesi_yang_diikuti>/<mata_kuliah>", views.session_fp2, name="session_fp2"),
    path("session_meb/<email>/<nama_lengkap>/<nomor_telefon>/<program_studi>/<angkatan>/<universitas>/<info_torche>/<metode_pembelajaran>/<jumlah_sesi_yang_diikuti>/<mata_kuliah>", views.session_meb, name="session_meb"),
    path("session_nce/<email>/<nama_lengkap>/<nomor_telefon>/<program_studi>/<angkatan>/<universitas>/<info_torche>/<metode_pembelajaran>/<jumlah_sesi_yang_diikuti>/<mata_kuliah>", views.session_nce, name="session_nce"),
    path("session_oce/<email>/<nama_lengkap>/<nomor_telefon>/<program_studi>/<angkatan>/<universitas>/<info_torche>/<metode_pembelajaran>/<jumlah_sesi_yang_diikuti>/<mata_kuliah>", views.session_oce, name="session_oce"),
    path("session_pcd/<email>/<nama_lengkap>/<nomor_telefon>/<program_studi>/<angkatan>/<universitas>/<info_torche>/<metode_pembelajaran>/<jumlah_sesi_yang_diikuti>/<mata_kuliah>", views.session_pcd, name="session_pcd"),
    path("session_pdd/<email>/<nama_lengkap>/<nomor_telefon>/<program_studi>/<angkatan>/<universitas>/<info_torche>/<metode_pembelajaran>/<jumlah_sesi_yang_diikuti>/<mata_kuliah>", views.session_pdd, name="session_pdd"),
    path("session_ped/<email>/<nama_lengkap>/<nomor_telefon>/<program_studi>/<angkatan>/<universitas>/<info_torche>/<metode_pembelajaran>/<jumlah_sesi_yang_diikuti>/<mata_kuliah>", views.session_ped, name="session_ped"),
    path("session_ppd/<email>/<nama_lengkap>/<nomor_telefon>/<program_studi>/<angkatan>/<universitas>/<info_torche>/<metode_pembelajaran>/<jumlah_sesi_yang_diikuti>/<mata_kuliah>", views.session_ppd, name="session_ppd"),
    path("session_tph/<email>/<nama_lengkap>/<nomor_telefon>/<program_studi>/<angkatan>/<universitas>/<info_torche>/<metode_pembelajaran>/<jumlah_sesi_yang_diikuti>/<mata_kuliah>", views.session_tph, name="session_tph"),

    path("lampiran/<email>/<nama_lengkap>/<nomor_telefon>/<program_studi>/<angkatan>/<universitas>/<info_torche>/<metode_pembelajaran>/<jumlah_sesi_yang_diikuti>/<mata_kuliah>/<materi>/<simulasi>/", views.lampiran, name="lampiran"),

    path("jumlah_peserta/<email>/<nama_lengkap>/<nomor_telefon>/<program_studi>/<angkatan>/<universitas>/<info_torche>/<metode_pembelajaran>/<jumlah_sesi_yang_diikuti>/<mata_kuliah>/<materi>/<simulasi>/<lampiran>/", views.jumlah_peserta, name="jumlah_peserta"),

    path("anggota_kelompok_1/<email>/<nama_lengkap>/<nomor_telefon>/<program_studi>/<angkatan>/<universitas>/<info_torche>/<metode_pembelajaran>/<jumlah_sesi_yang_diikuti>/<mata_kuliah>/<materi>/<simulasi>/<lampiran>/<jumlah_peserta>/", views.anggota_kelompok_1, name="anggota_kelompok_1"),
    path("anggota_kelompok_2/<email>/<nama_lengkap>/<nomor_telefon>/<program_studi>/<angkatan>/<universitas>/<info_torche>/<metode_pembelajaran>/<jumlah_sesi_yang_diikuti>/<mata_kuliah>/<materi>/<simulasi>/<lampiran>/<jumlah_peserta>/<email_1>/<nama_lengkap_1>/<nomor_telefon_1>/<akun_discord_1>/", views.anggota_kelompok_2, name="anggota_kelompok_2"),
    path("anggota_kelompok_3/<email>/<nama_lengkap>/<nomor_telefon>/<program_studi>/<angkatan>/<universitas>/<info_torche>/<metode_pembelajaran>/<jumlah_sesi_yang_diikuti>/<mata_kuliah>/<materi>/<simulasi>/<lampiran>/<jumlah_peserta>/<email_1>/<nama_lengkap_1>/<nomor_telefon_1>/<akun_discord_1>/<email_2>/<nama_lengkap_2>/<nomor_telefon_2>/<akun_discord_2>/", views.anggota_kelompok_3, name="anggota_kelompok_3"),
    path("anggota_kelompok_4/<email>/<nama_lengkap>/<nomor_telefon>/<program_studi>/<angkatan>/<universitas>/<info_torche>/<metode_pembelajaran>/<jumlah_sesi_yang_diikuti>/<mata_kuliah>/<materi>/<simulasi>/<lampiran>/<jumlah_peserta>/<email_1>/<nama_lengkap_1>/<nomor_telefon_1>/<akun_discord_1>/<email_2>/<nama_lengkap_2>/<nomor_telefon_2>/<akun_discord_2>/<email_3>/<nama_lengkap_3>/<nomor_telefon_3>/<akun_discord_3>/", views.anggota_kelompok_4, name="anggota_kelompok_4"),
    path("anggota_kelompok_5/<email>/<nama_lengkap>/<nomor_telefon>/<program_studi>/<angkatan>/<universitas>/<info_torche>/<metode_pembelajaran>/<jumlah_sesi_yang_diikuti>/<mata_kuliah>/<materi>/<simulasi>/<lampiran>/<jumlah_peserta>/<email_1>/<nama_lengkap_1>/<nomor_telefon_1>/<akun_discord_1>/<email_2>/<nama_lengkap_2>/<nomor_telefon_2>/<akun_discord_2>/<email_3>/<nama_lengkap_3>/<nomor_telefon_3>/<akun_discord_3>/<email_4>/<nama_lengkap_4>/<nomor_telefon_4>/<akun_discord_4>/", views.anggota_kelompok_5, name="anggota_kelompok_5"),
    path("anggota_kelompok_6/<email>/<nama_lengkap>/<nomor_telefon>/<program_studi>/<angkatan>/<universitas>/<info_torche>/<metode_pembelajaran>/<jumlah_sesi_yang_diikuti>/<mata_kuliah>/<materi>/<simulasi>/<lampiran>/<jumlah_peserta>/<email_1>/<nama_lengkap_1>/<nomor_telefon_1>/<akun_discord_1>/<email_2>/<nama_lengkap_2>/<nomor_telefon_2>/<akun_discord_2>/<email_3>/<nama_lengkap_3>/<nomor_telefon_3>/<akun_discord_3>/<email_4>/<nama_lengkap_4>/<nomor_telefon_4>/<akun_discord_4>/<email_5>/<nama_lengkap_5>/<nomor_telefon_5>/<akun_discord_5>/", views.anggota_kelompok_6, name="anggota_kelompok_6"),
    path("anggota_kelompok_7/<email>/<nama_lengkap>/<nomor_telefon>/<program_studi>/<angkatan>/<universitas>/<info_torche>/<metode_pembelajaran>/<jumlah_sesi_yang_diikuti>/<mata_kuliah>/<materi>/<simulasi>/<lampiran>/<jumlah_peserta>/<email_1>/<nama_lengkap_1>/<nomor_telefon_1>/<akun_discord_1>/<email_2>/<nama_lengkap_2>/<nomor_telefon_2>/<akun_discord_2>/<email_3>/<nama_lengkap_3>/<nomor_telefon_3>/<akun_discord_3>/<email_4>/<nama_lengkap_4>/<nomor_telefon_4>/<akun_discord_4>/<email_5>/<nama_lengkap_5>/<nomor_telefon_5>/<akun_discord_5>/<email_6>/<nama_lengkap_6>/<nomor_telefon_6>/<akun_discord_6>/", views.anggota_kelompok_7, name="anggota_kelompok_7"),
    path("anggota_kelompok_8/<email>/<nama_lengkap>/<nomor_telefon>/<program_studi>/<angkatan>/<universitas>/<info_torche>/<metode_pembelajaran>/<jumlah_sesi_yang_diikuti>/<mata_kuliah>/<materi>/<simulasi>/<lampiran>/<jumlah_peserta>/<email_1>/<nama_lengkap_1>/<nomor_telefon_1>/<akun_discord_1>/<email_2>/<nama_lengkap_2>/<nomor_telefon_2>/<akun_discord_2>/<email_3>/<nama_lengkap_3>/<nomor_telefon_3>/<akun_discord_3>/<email_4>/<nama_lengkap_4>/<nomor_telefon_4>/<akun_discord_4>/<email_5>/<nama_lengkap_5>/<nomor_telefon_5>/<akun_discord_5>/<email_6>/<nama_lengkap_6>/<nomor_telefon_6>/<akun_discord_6>/<email_7>/<nama_lengkap_7>/<nomor_telefon_7>/<akun_discord_7>/", views.anggota_kelompok_8, name="anggota_kelompok_8"),
    path("anggota_kelompok_9/<email>/<nama_lengkap>/<nomor_telefon>/<program_studi>/<angkatan>/<universitas>/<info_torche>/<metode_pembelajaran>/<jumlah_sesi_yang_diikuti>/<mata_kuliah>/<materi>/<simulasi>/<lampiran>/<jumlah_peserta>/<email_1>/<nama_lengkap_1>/<nomor_telefon_1>/<akun_discord_1>/<email_2>/<nama_lengkap_2>/<nomor_telefon_2>/<akun_discord_2>/<email_3>/<nama_lengkap_3>/<nomor_telefon_3>/<akun_discord_3>/<email_4>/<nama_lengkap_4>/<nomor_telefon_4>/<akun_discord_4>/<email_5>/<nama_lengkap_5>/<nomor_telefon_5>/<akun_discord_5>/<email_6>/<nama_lengkap_6>/<nomor_telefon_6>/<akun_discord_6>/<email_7>/<nama_lengkap_7>/<nomor_telefon_7>/<akun_discord_7>/<email_8>/<nama_lengkap_8>/<nomor_telefon_8>/<akun_discord_8>/", views.anggota_kelompok_9, name="anggota_kelompok_9"),
    path("anggota_kelompok_10/<email>/<nama_lengkap>/<nomor_telefon>/<program_studi>/<angkatan>/<universitas>/<info_torche>/<metode_pembelajaran>/<jumlah_sesi_yang_diikuti>/<mata_kuliah>/<materi>/<simulasi>/<lampiran>/<jumlah_peserta>/<email_1>/<nama_lengkap_1>/<nomor_telefon_1>/<akun_discord_1>/<email_2>/<nama_lengkap_2>/<nomor_telefon_2>/<akun_discord_2>/<email_3>/<nama_lengkap_3>/<nomor_telefon_3>/<akun_discord_3>/<email_4>/<nama_lengkap_4>/<nomor_telefon_4>/<akun_discord_4>/<email_5>/<nama_lengkap_5>/<nomor_telefon_5>/<akun_discord_5>/<email_6>/<nama_lengkap_6>/<nomor_telefon_6>/<akun_discord_6>/<email_7>/<nama_lengkap_7>/<nomor_telefon_7>/<akun_discord_7>/<email_8>/<nama_lengkap_8>/<nomor_telefon_8>/<akun_discord_8>/<email_9>/<nama_lengkap_9>/<nomor_telefon_9>/<akun_discord_9>/", views.anggota_kelompok_10, name="anggota_kelompok_10"),

    path("jadwal_belajar/<email>/<nama_lengkap>/<nomor_telefon>/<program_studi>/<angkatan>/<universitas>/<info_torche>/<metode_pembelajaran>/<jumlah_sesi_yang_diikuti>/<mata_kuliah>/<materi>/<simulasi>/<lampiran>/<jumlah_peserta>/<email_1>/<nama_lengkap_1>/<nomor_telefon_1>/<akun_discord_1>/<email_2>/<nama_lengkap_2>/<nomor_telefon_2>/<akun_discord_2>/<email_3>/<nama_lengkap_3>/<nomor_telefon_3>/<akun_discord_3>/<email_4>/<nama_lengkap_4>/<nomor_telefon_4>/<akun_discord_4>/<email_5>/<nama_lengkap_5>/<nomor_telefon_5>/<akun_discord_5>/<email_6>/<nama_lengkap_6>/<nomor_telefon_6>/<akun_discord_6>/<email_7>/<nama_lengkap_7>/<nomor_telefon_7>/<akun_discord_7>/<email_8>/<nama_lengkap_8>/<nomor_telefon_8>/<akun_discord_8>/<email_9>/<nama_lengkap_9>/<nomor_telefon_9>/<akun_discord_9>/<email_10>/<nama_lengkap_10>/<nomor_telefon_10>/<akun_discord_10>/", views.jadwal_belajar, name="jadwal_belajar"),

    path("invoice_assignment_q1/Inv/<jumlah_peserta_invoice>/<metode_pembelajaran_invoice>/<mata_kuliah_invoice>/<registration_number_q1_invoice>/<quartal_invoice>/", views.invoice_assignment_q1, name="invoice_assignment_q1"),
    path("invoice_assignment_q2/Inv/<jumlah_peserta_invoice>/<metode_pembelajaran_invoice>/<mata_kuliah_invoice>/<registration_number_q2_invoice>/<quartal_invoice>/", views.invoice_assignment_q2, name="invoice_assignment_q2"),
    path("invoice_assignment_q3/Inv/<jumlah_peserta_invoice>/<metode_pembelajaran_invoice>/<mata_kuliah_invoice>/<registration_number_q3_invoice>/<quartal_invoice>/", views.invoice_assignment_q3, name="invoice_assignment_q3"),
    path("invoice_assignment_q4/Inv/<jumlah_peserta_invoice>/<metode_pembelajaran_invoice>/<mata_kuliah_invoice>/<registration_number_q4_invoice>/<quartal_invoice>/", views.invoice_assignment_q4, name="invoice_assignment_q4"),

    #path("invoice_q1/Inv/<jumlah_peserta_invoice>/<metode_pembelajaran_invoice>/<mata_kuliah_invoice>/<registration_number_q1_invoice>/<quartal_invoice>/", views.invoice_q1, name="invoice_q1"),
    #path("invoice_q2/Inv/<jumlah_peserta_invoice>/<metode_pembelajaran_invoice>/<mata_kuliah_invoice>/<registration_number_q2_invoice>/<quartal_invoice>/", views.invoice_q2, name="invoice_q2"),
    #path("invoice_q3/Inv/<jumlah_peserta_invoice>/<metode_pembelajaran_invoice>/<mata_kuliah_invoice>/<registration_number_q3_invoice>/<quartal_invoice>/", views.invoice_q3, name="invoice_q3"),
    #path("invoice_q4/Inv/<jumlah_peserta_invoice>/<metode_pembelajaran_invoice>/<mata_kuliah_invoice>/<registration_number_q4_invoice>/<quartal_invoice>/", views.invoice_q4, name="invoice_q4"),
    path('get_data/', views.get_data, name='get_data'),

    path('pendaftaran_berhasil/<nama_lengkap>/<email>/<nomor_telefon>/<program_studi>/<universitas>/<metode_pembelajaran>/<mata_kuliah>/<materi>/<jumlah_peserta_invoice>/<metode_pembelajaran_invoice>/<mata_kuliah_invoice>/<registration_number_q1_invoice>/<quartal_invoice>/', views.send_email_q1, name='send_email_q1'),
    path('pendaftaran_berhasil/<nama_lengkap>/<email>/<nomor_telefon>/<program_studi>/<universitas>/<metode_pembelajaran>/<mata_kuliah>/<materi>/<jumlah_peserta_invoice>/<metode_pembelajaran_invoice>/<mata_kuliah_invoice>/<registration_number_q2_invoice>/<quartal_invoice>/', views.send_email_q2, name='send_email_q2'),
    path('pendaftaran_berhasil/<nama_lengkap>/<email>/<nomor_telefon>/<program_studi>/<universitas>/<metode_pembelajaran>/<mata_kuliah>/<materi>/<jumlah_peserta_invoice>/<metode_pembelajaran_invoice>/<mata_kuliah_invoice>/<registration_number_q3_invoice>/<quartal_invoice>/', views.send_email_q3, name='send_email_q3'),
    path('pendaftaran_berhasil/<nama_lengkap>/<email>/<nomor_telefon>/<program_studi>/<universitas>/<metode_pembelajaran>/<mata_kuliah>/<materi>/<jumlah_peserta_invoice>/<metode_pembelajaran_invoice>/<mata_kuliah_invoice>/<registration_number_q4_invoice>/<quartal_invoice>/', views.send_email_q4, name='send_email_q4'),

    path('pendaftaran_berhasil/', views.pendaftaran_berhasil, name='pendaftaran_berhasil'), 
    path('pendaftaran_gagal/', views.pendaftaran_gagal, name='pendaftaran_gagal'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)